services:
  manager-nginx:
    build:
      context: ./manager/docker/development
      dockerfile: nginx.docker
    restart: always
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
    networks:
      - manager
  manager-php-fpm:
    build:
      context: ./manager/docker/development
      dockerfile: php-fpm.docker
    restart: always
    volumes:
      - ./manager:/app
      - ./manager/docker/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - manager
  manager-php-cli:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    restart: always
    volumes:
      - ./manager:/app
      - ./manager/docker/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - composer:/root/.composer/cache
    networks:
      - manager
  manager-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: manager
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - manager
  manager-mailpit:
    image: 'axllent/mailpit:latest'
    restart: always
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - manager
  manager-messenger-worker:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    depends_on:
      - manager-postgres
      - manager-redis
      - manager-mailpit
    command: php bin/console messenger:consume async
    restart: unless-stopped
    environment:
      MAILER_DSN: ${MAILER_DSN}
    env_file:
      - ./manager/.env
    volumes:
      - ./manager:/app
      - composer:/root/.composer/cache
    networks:
      - manager
  manager-redis:
    image: redis:latest
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    restart: always
    volumes:
      - manager-redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'
    networks:
      - manager
  manager-vite:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    restart: always
    working_dir: /app
    command: npm run dev -- --host
    volumes:
      - ./manager:/app
    ports:
      - "5173:5173"
    networks:
      - manager
    depends_on:
      - manager-php-fpm
  centrifugo:
    image: centrifugo/centrifugo:v6
    restart: always
    networks:
      - manager
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./centrifugo/docker/development/centrifugo/config.json:/centrifugo/config.json
    ports:
      - "8083:8000"
    command: centrifugo -c config.json
#    command: centrifugo  --admin_insecure

volumes:
  composer:
  pgdata:
  manager-redis:

networks:
  manager:
