doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            user_user_id: App\Model\User\Entity\User\IdType
            user_user_email: App\Model\User\Entity\User\EmailType
            user_user_role: App\Model\User\Entity\User\RoleType
            work_members_group_id: App\Model\Work\Entity\Members\Group\IdType
            work_members_member_id: App\Model\Work\Entity\Members\Member\IdType
            work_members_member_email: App\Model\Work\Entity\Members\Member\EmailType
            work_members_member_status: App\Model\Work\Entity\Members\Member\StatusType
            work_projects_role_id: App\Model\Work\Entity\Projects\Role\IdType
            work_projects_role_permissions: App\Model\Work\Entity\Projects\Role\PermissionsType
            work_projects_project_id: App\Model\Work\Entity\Projects\Project\IdType
            work_projects_project_status: App\Model\Work\Entity\Projects\Project\StatusType
            work_projects_project_department_id: App\Model\Work\Entity\Projects\Project\Department\IdType
            work_projects_task_id: App\Model\Work\Entity\Projects\Task\IdType
            work_projects_task_type: App\Model\Work\Entity\Projects\Task\TypeType
            work_projects_task_status: App\Model\Work\Entity\Projects\Task\StatusType
            work_projects_task_file_id: App\Model\Work\Entity\Projects\Task\File\IdType
            work_projects_task_change_id: App\Model\Work\Entity\Projects\Task\Change\IdType
            comment_comment_id: App\Model\Comment\Entity\Comment\IdType
            comment_comment_author_id: App\Model\Comment\Entity\Comment\AuthorIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/User/Entity/User'
                prefix: 'App\Model\User\Entity\User'
                alias: User
            Comment:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Model/Comment/Entity'
                prefix: 'App\Model\Comment\Entity'
                alias: Work
            Work:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Model/Work/Entity'
                prefix: 'App\Model\Work\Entity'
                alias: Work
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
