knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: oauth.facebook_check
            graph_api_version: v19.0
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google_main:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: oauth.google_check
            redirect_params: {}
